<script setup>
import { Barcode, Camera, Upload, LoaderCircle, X, ArrowRight, ScanLine } from 'lucide-vue-next'
import { detectBarcodeCanvas, normalizeBarcode } from '~/utils/barcode'
import { prepareWinePhoto } from '~/utils/prepareWinePhoto'
const emit=defineEmits(['recognized','manual','label'])
const video=ref(null),photoInput=ref(null),cameraInput=ref(null),code=ref(''),live=ref(false),starting=ref(false),busy=ref(false),reading=ref(false),error=ref(''),photoURL=ref('')
let stream=null,timer=null,session=0,request=null,photoVersion=0
const valid=computed(()=>normalizeBarcode(code.value))
function stop(){session++;clearTimeout(timer);stream?.getTracks().forEach(track=>track.stop());stream=null;live.value=false;starting.value=false}
function hidden(){if(document.hidden)stop()}
onMounted(()=>document.addEventListener('visibilitychange',hidden))
onBeforeUnmount(()=>{photoVersion++;stop();request?.abort();if(photoURL.value)URL.revokeObjectURL(photoURL.value);document.removeEventListener('visibilitychange',hidden)})
async function lookup(){if(!valid.value){error.value='Enter a valid EAN/UPC barcode with 8, 12, or 13 digits.';return}stop();request?.abort();const controller=new AbortController();request=controller;busy.value=true;error.value='';try{const result=await $fetch(`/api/barcodes/${valid.value}`,{signal:controller.signal,retry:0,timeout:18000});if(!controller.signal.aborted)emit('recognized',result)}catch(e){if(!controller.signal.aborted)error.value=typeof e.data==='string'?e.data:'Barcode lookup failed. Try again or use a label photo.'}finally{if(request===controller)busy.value=false}}
async function start(){
 stop();error.value=''
 if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia){error.value='Live camera scanning needs HTTPS (or localhost). Use “Take barcode photo” here, or open the app over HTTPS.';return}
 const current=session;starting.value=true
 try{const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});if(current!==session){media.getTracks().forEach(track=>track.stop());return};stream=media;live.value=true;await nextTick();video.value.srcObject=media;await video.value.play();starting.value=false
  const canvas=document.createElement('canvas'),began=Date.now()
  async function tick(){if(current!==session||!live.value)return;try{if(video.value?.readyState>=2){const ratio=Math.min(1,1000/video.value.videoWidth);canvas.width=Math.round(video.value.videoWidth*ratio);canvas.height=Math.round(video.value.videoHeight*ratio);canvas.getContext('2d').drawImage(video.value,0,0,canvas.width,canvas.height);const found=await detectBarcodeCanvas(canvas);if(current!==session)return;if(found){code.value=found;stop();await lookup();return}}}catch{/* Keep scanning while the camera adjusts focus. */}if(Date.now()-began>30000){stop();error.value='No barcode found yet. Try a close-up barcode photo or type the number below.';return}timer=setTimeout(tick,300)}
  tick()
 }catch(e){if(current!==session)return;stop();error.value=e.name==='NotAllowedError'?'Camera access was not allowed. Use a barcode photo or enter the number below.':'Could not open the camera. Try a barcode photo instead.'}
}
async function fileChanged(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;stop();request?.abort();busy.value=false;const current=++photoVersion;reading.value=true;code.value='';error.value='';try{const blob=await prepareWinePhoto(file);if(current!==photoVersion)return;if(photoURL.value)URL.revokeObjectURL(photoURL.value);photoURL.value=URL.createObjectURL(blob);const img=await new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=reject;image.src=photoURL.value});const canvas=document.createElement('canvas');canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;canvas.getContext('2d').drawImage(img,0,0);const found=await detectBarcodeCanvas(canvas);if(current!==photoVersion)return;if(!found){error.value='No readable EAN/UPC barcode found. Include all bars and white space on both sides, hold the camera parallel to the label, or enter the number below.';return};code.value=found;await lookup()}catch(e){if(current===photoVersion)error.value=e.message||'Could not read this photo. Choose another image.'}finally{if(current===photoVersion)reading.value=false}}
function manual(){stop();request?.abort();emit('manual',valid.value||'')}
</script>

<template>
 <div class="barcode-scanner"><div class="barcode-camera-panel"><div class="barcode-camera-view"><video v-if="live" ref="video" autoplay muted playsinline aria-label="Live barcode camera"></video><img v-else-if="photoURL" :src="photoURL" alt="Selected barcode photo"/><div v-else class="barcode-placeholder"><Barcode :size="100" :stroke-width="1"/><h3>Find your wine by its barcode.</h3><p>Scan the EAN or UPC code on the back label.</p></div><div v-if="live" class="barcode-guide" aria-hidden="true"><span></span></div><div v-if="reading||starting" class="preparing-overlay"><LoaderCircle :size="24" class="spinning"/><span>{{starting?'Opening camera…':'Reading barcode…'}}</span></div><button v-if="live||starting" class="stop-camera" aria-label="Stop camera" @click="stop"><X :size="17"/></button></div>
  <button class="primary barcode-live-button" :disabled="busy||reading||starting" @click="live?stop():start()"><Camera :size="17"/>{{live?'Stop live camera':'Start live camera'}}</button><div class="photo-source-buttons"><button class="editor-secondary" :disabled="busy||reading" @click="cameraInput.click()"><Camera :size="16"/>Take barcode photo</button><button class="editor-secondary" :disabled="busy||reading" @click="photoInput.click()"><Upload :size="16"/>Upload barcode</button></div><input ref="cameraInput" class="scanner-file-input" type="file" accept="image/*" capture="environment" aria-label="Take a barcode photo" @change="fileChanged"/><input ref="photoInput" class="scanner-file-input" type="file" accept="image/*" aria-label="Upload a barcode image" @change="fileChanged"/><p class="photo-privacy">Barcodes are decoded on your device. Only the barcode number is sent for lookup. No OpenAI key is needed.</p></div>
  <div class="barcode-lookup-panel"><span class="little-label">SCAN. CHECK. CELLAR.</span><h3>A shortcut to<br>your next discovery.</h3><p>We’ll check bottles already in your cellar, then the Open Food Facts catalogue.</p><form @submit.prevent="lookup"><label>Barcode number<input v-model="code" inputmode="numeric" autocomplete="off" maxlength="20" placeholder="e.g. 5901234123457" :disabled="busy||reading"/></label><button class="primary" :disabled="!valid||busy||reading"><LoaderCircle v-if="busy" :size="16" class="spinning"/><Barcode v-else :size="17"/>{{busy?'Looking up wine…':'Look up barcode'}}</button></form><div v-if="error" class="scanner-error" role="alert">{{error}}</div><div class="barcode-vintage-note"><strong>Check the vintage on your bottle.</strong><p>One barcode can be used for several vintages. We’ll leave the year for you to confirm.</p></div><p class="barcode-coverage">Not every wine is listed. If there’s no match, a front-label photo or manual entry can still get it into your cellar.</p><button class="scanner-manual" :disabled="busy||reading" @click="emit('label')"><ScanLine :size="15"/>Use a label photo instead</button><button class="scanner-manual" :disabled="busy||reading" @click="manual">Enter wine details manually<ArrowRight :size="14"/></button><a class="barcode-attribution" href="https://world.openfoodfacts.org" target="_blank" rel="noopener noreferrer">Catalogue: Open Food Facts · ODbL</a></div></div>
</template>
