<script setup>
import { money, purchaseSummary } from '~/utils/purchases'
const emit=defineEmits(['select']),entries=ref([]),loading=ref(false),error=ref(''),seller=ref(''),query=ref('')
const summary=computed(()=>purchaseSummary(entries.value))
const sellers=computed(()=>[...new Set(entries.value.map(e=>e.seller).filter(Boolean))].sort())
const filtered=computed(()=>entries.value.filter(e=>(!seller.value||e.seller===seller.value)&&`${e.name} ${e.seller} ${e.purchaseDate}`.toLowerCase().includes(query.value.toLowerCase())))
async function load(){loading.value=true;error.value='';try{entries.value=await $fetch('/api/purchases')}catch{error.value='Could not load purchases. Please try again.'}finally{loading.value=false}}
onMounted(load)
</script>
<template><section class="panel purchase-tracker"><header><h2>Purchases & spending</h2><p>Recorded purchase costs, including enjoyed bottles. Currencies are shown separately; missing prices and dates are excluded from the corresponding totals. This is purchase cost, not market value.</p></header><p v-if="loading" role="status">Loading purchases…</p><p v-if="error" class="scanner-error" role="alert">{{error}} <button @click="load">Retry</button></p><template v-if="!loading&&!error"><div class="purchase-totals"><article v-for="total in summary.totals" :key="total.currency"><span>{{total.currency}}</span><h3>{{money(total.total,total.currency)}}</h3><p>Total recorded spending · {{total.bottles}} priced bottles</p><strong>{{money(total.cellar,total.currency)}}</strong><p>Cost of bottles still in the cellar</p><p v-if="total.undated">{{money(total.undated,total.currency)}} has no purchase date</p></article></div><p v-if="!entries.length" class="empty">No purchase details recorded yet. Add them when storing a wine or open a bottle and choose Edit purchase details.</p><h3 v-if="summary.months.length">Spending by month</h3><div class="monthly-spending"><div v-for="month in summary.months" :key="month.month+month.currency"><span>{{month.month}} · {{month.currency}}</span><strong>{{money(month.amount,month.currency)}}</strong><small>{{month.bottles}} bottles</small></div></div><div v-if="entries.length" class="purchase-filters"><label>Search purchases<input v-model="query" placeholder="Wine, seller, or date"></label><label>Seller<select v-model="seller" aria-label="Filter purchases by seller"><option value="">All sellers</option><option v-for="name in sellers" :key="name">{{name}}</option></select></label></div><ol class="purchase-list"><li v-for="entry in filtered" :key="entry.bottleId"><div><button v-if="entry.inCellar" @click="emit('select',entry.bottleId)">{{entry.name}}</button><strong v-else>{{entry.name}}</strong><p>{{entry.vintage||'NV'}} · {{entry.seller||'Seller unknown'}} · {{entry.purchaseDate||'Date unknown'}} · {{entry.inCellar?'In cellar':'Enjoyed'}}</p></div><strong>{{entry.priceMinor==null?'Price unknown':money(entry.priceMinor,entry.currency)}}</strong></li></ol><p v-if="entries.length&&!filtered.length" class="empty">No purchases match these filters.</p></template></section></template>
<style scoped>.purchase-tracker{padding:24px}.purchase-tracker header p{font-size:12px;color:#857b70;line-height:1.6;margin:12px 0}.purchase-totals{display:flex;gap:16px;flex-wrap:wrap;margin:20px 0}.purchase-totals article{background:#f8f3ea;border:1px solid #e8e0d6;border-radius:8px;padding:18px;flex:1;min-width:200px}.purchase-totals h3{font-size:24px;margin:10px 0}.purchase-totals p{font-size:12px;color:#857b70;margin:8px 0}.monthly-spending{display:flex;flex-wrap:wrap;gap:12px;margin:16px 0}.monthly-spending>div{display:flex;flex-direction:column;gap:6px;border:1px solid #e8e0d6;border-radius:6px;padding:12px}.monthly-spending small{color:#857b70}.purchase-filters{display:flex;gap:16px;margin:20px 0;flex-wrap:wrap}.purchase-filters label{flex:1;min-width:160px}.purchase-list{list-style:none;padding:0}.purchase-list li{display:flex;justify-content:space-between;gap:16px;border-top:1px solid #e8e0d6;padding:18px 0}.purchase-list button{padding:0;text-decoration:underline;text-align:left}.purchase-list p{font-size:12px;color:#857b70;line-height:1.6;margin-top:6px}.purchase-list li>strong{white-space:nowrap}@media(max-width:600px){.purchase-tracker{padding:18px}.purchase-list li{flex-wrap:wrap}.purchase-list li>div{min-width:0;overflow-wrap:anywhere}}
</style>
