<script setup>
import { X, Check, Move, RotateCw, Undo2, Map, DoorOpen, Armchair, Grid2X2, AlertCircle } from 'lucide-vue-next'
import { layoutIssue } from '~/utils/layout'
const props=defineProps({cellar:{type:Object,required:true}}),emit=defineEmits(['close','saved'])
const clone=()=>JSON.parse(JSON.stringify(props.cellar))
const draft=ref(clone()),selected=ref('room'),snap=ref(true),busy=ref(false),error=ref(''),root=ref(null)
const shelf=computed(()=>draft.value.racks.find(r=>r.id===selected.value))
const issue=computed(()=>layoutIssue(draft.value))
const dirty=computed(()=>JSON.stringify(draft.value)!==JSON.stringify(props.cellar))
useEditorDialog(root,()=>{if(!busy.value)emit('close')})
function move({id,x,y}){if(busy.value)return;if(id==='table'){draft.value.layout.tableX=x;draft.value.layout.tableY=y}else{const r=draft.value.racks.find(r=>r.id===id);r.x=x;r.y=y}}
function reset(){draft.value=clone();selected.value='room';error.value=''}
async function save(){if(issue.value||busy.value)return;busy.value=true;error.value='';try{const {revision,name,room,width,depth,layout,racks}=draft.value;await $fetch('/api/cellar/layout',{method:'PUT',body:{revision,name,room,width,depth,layout,racks}});emit('saved')}catch(e){error.value=typeof e.data==='string'?e.data:'Could not save your layout. Please try again.'}finally{busy.value=false}}
</script>

<template>
 <div class="editor-backdrop"><section ref="root" class="layout-editor" role="dialog" aria-modal="true" aria-label="Room layout editor" tabindex="-1">
  <header class="editor-header"><div class="editor-heading-icon"><Map :size="23"/></div><div><span class="eyebrow">MAKE THE SPACE YOURS</span><h2>Room layout editor <span>Bird’s-eye view</span></h2></div><button class="editor-close" aria-label="Close room editor" :disabled="busy" @click="emit('close')"><X :size="21"/></button></header>
  <div class="layout-editor-body"><div class="editor-workspace"><div class="canvas-toolbar"><span><Move :size="15"/>Drag to arrange · Arrow keys to fine-tune</span><label><input v-model="snap" type="checkbox"/>Snap to 10 cm</label></div><div class="editor-canvas-wrap"><CellarPlan :room="draft" :selected="selected" :editable="!busy" :snap="snap" @select="selected=$event" @move="move"/></div><div class="canvas-caption"><span><i class="legend-box gold-outline"></i> Selected object</span><span>All measurements in meters · True scale</span></div><div v-if="issue" class="editor-alert" role="status"><AlertCircle :size="17"/>{{issue}}</div><div v-else class="editor-valid"><Check :size="15"/>Everything fits. Your entrance is clear.</div></div>
   <aside class="editor-inspector"><div class="inspector-tabs"><button :class="{active:selected==='room'}" @click="selected='room'"><Map :size="15"/>Room</button><button :class="{active:selected==='door'}" @click="selected='door'"><DoorOpen :size="15"/>Door</button><button :class="{active:selected==='table'}" @click="selected='table'"><Armchair :size="15"/>Table</button></div>
    <fieldset :disabled="busy">
     <template v-if="selected==='room'"><div class="inspector-title"><h3>Room & walls</h3><p>Start with the shape of your space.</p></div><label>Cellar name<input v-model="draft.name" maxlength="100"/></label><label>Room label<input v-model="draft.room" maxlength="80"/></label><div class="editor-field-row"><label>Room width (m)<input v-model.number="draft.width" type="number" min="2" max="30" step=".1"/></label><label>Room depth (m)<input v-model.number="draft.depth" type="number" min="2" max="30" step=".1"/></label></div><label>Room shape<select v-model="draft.layout.shape"><option value="rectangle">Rectangle</option><option value="l-shape">L-shaped · northeast cutout</option></select></label><div v-if="draft.layout.shape==='l-shape'" class="editor-field-row"><label>Cutout width (m)<input v-model.number="draft.layout.cutoutWidth" type="number" min=".3" :max="draft.width-1" step=".1"/></label><label>Cutout depth (m)<input v-model.number="draft.layout.cutoutDepth" type="number" min=".3" :max="draft.depth-1" step=".1"/></label></div><label>Floor material<select v-model="draft.layout.floor"><option value="stone">Natural stone</option><option value="wood">Warm oak</option><option value="concrete">Concrete</option></select></label><p class="inspector-note">Select a shelf on the plan to move, resize, or rotate its footprint.</p></template>
     <template v-else-if="selected==='door'"><div class="inspector-title"><h3>A welcoming entrance</h3><p>Position the door along an outer wall.</p></div><label>Door wall<select v-model="draft.layout.doorWall"><option value="north">North wall</option><option value="east">East wall</option><option value="south">South wall</option><option value="west">West wall</option></select></label><label>Door offset (m)<input v-model.number="draft.layout.doorOffset" type="number" min="0" step=".1"/></label><label>Door width (m)<input v-model.number="draft.layout.doorWidth" type="number" min=".6" max="2" step=".1"/></label><p class="inspector-note">Offset is measured from the left for north/south walls, and from the top for east/west walls. Keep 0.5 m clear inside the entrance.</p></template>
     <template v-else-if="selected==='table'"><div class="inspector-title"><h3>The tasting table</h3><p>A little space to enjoy your collection.</p></div><label class="editor-checkbox"><input v-model="draft.layout.tableEnabled" type="checkbox"/>Include a tasting table</label><template v-if="draft.layout.tableEnabled"><div class="editor-field-row"><label>Table X (m)<input v-model.number="draft.layout.tableX" type="number" min="0" step=".1"/></label><label>Table Y (m)<input v-model.number="draft.layout.tableY" type="number" min="0" step=".1"/></label></div><div class="editor-field-row"><label>Table width (m)<input v-model.number="draft.layout.tableWidth" type="number" min=".4" max="5" step=".1"/></label><label>Table depth (m)<input v-model.number="draft.layout.tableDepth" type="number" min=".4" max="5" step=".1"/></label></div><p class="inspector-note">Drag the table on the plan to find its place.</p></template></template>
     <template v-else-if="shelf"><div class="inspector-title"><span class="eyebrow">SHELF {{shelf.id}}</span><h3>{{shelf.name}}</h3><p>Change its position and physical footprint.</p></div><div class="editor-field-row"><label>Shelf X (m)<input v-model.number="shelf.x" type="number" min="0" step=".1"/></label><label>Shelf Y (m)<input v-model.number="shelf.y" type="number" min="0" step=".1"/></label></div><div class="editor-field-row"><label>Shelf width (m)<input v-model.number="shelf.width" type="number" min=".2" max="10" step=".1"/></label><label>Shelf depth (m)<input v-model.number="shelf.depth" type="number" min=".2" max="10" step=".1"/></label></div><button class="editor-secondary full-width" @click="shelf.rotation=shelf.rotation===90?0:90"><RotateCw :size="16"/>Rotate 90° <span>{{shelf.rotation}}°</span></button><p class="inspector-note">This changes the footprint on the floor. Bottle rows and columns are configured in the shelf editor.</p></template>
    </fieldset>
    <div class="inspector-shelves"><span class="little-label">SHELVES IN THIS ROOM</span><button v-for="r in draft.racks" :key="r.id" :class="{active:selected===r.id}" @click="selected=r.id"><span class="rack-letter">{{r.id}}</span><span>{{r.short}}</span><Grid2X2 :size="14"/></button><p v-if="!draft.racks.length" class="inspector-note">Save your room, then choose “Add shelf” to furnish it.</p></div>
   </aside>
  </div>
  <footer class="editor-footer"><div><span :class="['draft-dot',{changed:dirty}]"></span>{{dirty?'Unsaved layout changes':'Your saved layout'}}<span class="editor-save-error" v-if="error" role="alert">{{error}}</span></div><button class="editor-secondary" :disabled="busy||!dirty" @click="reset"><Undo2 :size="15"/>Reset</button><button class="editor-secondary" :disabled="busy" @click="emit('close')">Cancel</button><button class="primary" :disabled="busy||!!issue||!dirty" @click="save"><Check :size="16"/>{{busy?'Saving…':'Save layout'}}</button></footer>
 </section></div>
</template>
