<script setup>
import { X, Grid2X2, Check, Wine, Trash2, AlertCircle } from 'lucide-vue-next'
const props=defineProps({cellar:{type:Object,required:true},shelf:{type:Object,default:null}}),emit=defineEmits(['close','saved'])
const root=ref(null),busy=ref(false),error=ref(''),confirmRemove=ref(false)
const draft=reactive(props.shelf?{name:props.shelf.name,short:props.shelf.short,wall:props.shelf.wall,grapes:props.shelf.grapes,temp:props.shelf.temp,color:props.shelf.color,rows:props.shelf.rows,columns:props.shelf.columns}:{name:'New shelf',short:'New shelf',wall:'Freestanding',grapes:'',temp:13,color:'red',rows:5,columns:6})
const bottles=computed(()=>props.cellar.bottles.filter(b=>b.rack===props.shelf?.id)),capacity=computed(()=>Math.max(0,Math.min(400,Number(draft.rows)*Number(draft.columns)||0)))
const removed=computed(()=>bottles.value.filter(b=>b.slot>=capacity.value))
const issue=computed(()=>!draft.name.trim()||!draft.short.trim()||!draft.wall.trim()?'Enter a shelf name, short label, and location.':!Number.isInteger(draft.rows)||!Number.isInteger(draft.columns)||draft.rows<1||draft.columns<1||draft.rows>20||draft.columns>20?'Choose between 1 and 20 rows and columns.':removed.value.length?`${removed.value.length} occupied ${removed.value.length===1?'slot would':'slots would'} be removed. Keep a larger shelf or empty those slots first.`:'')
const columnCount=computed(()=>Math.max(1,Math.min(20,Number(draft.columns)||1)))
const bottleAt=slot=>bottles.value.find(b=>b.slot===slot)
useEditorDialog(root,()=>{if(!busy.value)emit('close')})
async function save(){if(issue.value)return;busy.value=true;error.value='';try{await $fetch(props.shelf?`/api/racks/${encodeURIComponent(props.shelf.id)}`:'/api/racks',{method:props.shelf?'PUT':'POST',body:{...draft,revision:props.cellar.revision}});emit('saved')}catch(e){error.value=typeof e.data==='string'?e.data:'Could not save your shelf. Please try again.'}finally{busy.value=false}}
async function remove(){busy.value=true;error.value='';try{await $fetch(`/api/racks/${encodeURIComponent(props.shelf.id)}`,{method:'DELETE',body:{revision:props.cellar.revision}});emit('saved')}catch(e){error.value=typeof e.data==='string'?e.data:'Could not remove this shelf.'}finally{busy.value=false}}
</script>

<template>
 <div class="editor-backdrop"><section ref="root" class="shelf-editor" role="dialog" aria-modal="true" :aria-label="shelf?'Shelf editor':'Add shelf'" tabindex="-1"><header class="editor-header"><div class="editor-heading-icon"><Grid2X2 :size="23"/></div><div><span class="eyebrow">A PLACE FOR EVERY BOTTLE</span><h2>{{shelf?`Edit shelf ${shelf.id}`:'Add a shelf'}}</h2></div><button class="editor-close" aria-label="Close shelf editor" :disabled="busy" @click="emit('close')"><X :size="21"/></button></header>
  <div class="shelf-editor-body"><div class="shelf-preview"><div class="preview-title"><span class="little-label">LIVE SHELF PREVIEW</span><span>{{draft.rows}} rows × {{draft.columns}} columns</span></div><h3>{{draft.name || 'Your shelf'}}</h3><p>{{bottles.length}} bottles stored <span>·</span> {{capacity}} total slots</p><div class="shelf-grid-scroll"><div class="shelf-preview-grid" :style="{'--columns':columnCount,minWidth:columnCount>8?columnCount*40+'px':undefined}"><div class="shelf-column-labels"><span v-for="n in columnCount">{{String.fromCharCode(64+n)}}</span></div><div class="shelf-slot-grid"><div v-for="slot in capacity" :key="slot" :class="['shelf-preview-slot',{occupied:bottleAt(slot-1)},draft.color]" :title="bottleAt(slot-1)?.name || `Empty slot ${slot}`"><span v-if="bottleAt(slot-1)" class="bottle-cork"></span><span v-else class="empty-slot-number">{{slot}}</span></div></div></div></div><div class="shelf-preview-legend"><span><i class="legend-box burgundy"></i> Stored bottle</span><span><i class="legend-circle"></i> Available slot</span></div><div v-if="issue" class="editor-alert" role="status"><AlertCircle :size="17"/>{{issue}}</div><div v-else class="shelf-preserved"><Wine :size="18"/><p>{{shelf?'Your bottles keep their slot numbers.':'Your new shelf starts empty.'}}<small>{{shelf?'Changing columns changes the displayed row/column addresses.':'We’ll place it in a free spot. Arrange it in the room editor.'}}</small></p></div></div>
   <fieldset class="shelf-fields" :disabled="busy"><label>Shelf name<input v-model="draft.name" maxlength="100"/></label><div class="editor-field-row"><label>Short label<input v-model="draft.short" maxlength="40"/></label><label>Location<input v-model="draft.wall" maxlength="60"/></label></div><label>Wines & grape varieties<textarea v-model="draft.grapes" rows="2" maxlength="200" placeholder="Pinot Noir, Syrah & your favorites"/></label><div class="field-divider"></div><div class="editor-field-row"><label>Rows<input v-model.number="draft.rows" type="number" min="1" max="20"/></label><label>Columns<input v-model.number="draft.columns" type="number" min="1" max="20"/></label></div><div class="capacity-summary"><span>Storage capacity</span><strong>{{capacity}} bottles</strong></div><div class="editor-field-row"><label>Shelf color<select v-model="draft.color"><option value="red">Burgundy</option><option value="white">Olive</option><option value="gold">Gold</option></select></label></div><p class="inspector-note">Set the shelf’s physical footprint and position in the room editor.</p>
   <div v-if="shelf" class="remove-shelf"><button v-if="!confirmRemove" class="danger-button" :disabled="bottles.length>0" @click="confirmRemove=true"><Trash2 :size="15"/>Remove shelf</button><p v-if="bottles.length">Empty this shelf before removing it.</p><template v-if="confirmRemove"><p>Remove this empty shelf from your cellar?</p><div><button class="danger-button" @click="remove">Yes, remove shelf</button><button class="editor-secondary" @click="confirmRemove=false">Keep shelf</button></div></template></div></fieldset></div>
  <footer class="editor-footer"><div><span v-if="error" class="editor-save-error" role="alert">{{error}}</span><span v-else>Changes are saved when you’re ready.</span></div><button class="editor-secondary" :disabled="busy" @click="emit('close')">Cancel</button><button class="primary" :disabled="busy||!!issue" @click="save"><Check :size="16"/>{{busy?'Saving…':shelf?'Save shelf':'Create shelf'}}</button></footer>
 </section></div>
</template>
